name: Rename Folder nexichat to GONI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename_folder_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rename folder nexichat to GONI
        run: |
          # Ensure the folder exists before trying to rename it
          if [ -d "nexichat" ]; then
            mv nexichat GONI
            find . -type f -name "*.py" -exec sed -i 's/nexichat/GONI/g' {} +
          else
            echo "Folder nexichat does not exist."
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'Gokukhan1'
          git config --global user.email 'Gokukhan1@users.noreply.github.com'
          git add .
          git commit -m "Initial commit " || echo "No changes to commit"
          git push

          
